const ranges = require('./ranges');

module.exports = {
  btc: {
    key: 'btc',
    symbol: 'BTC',
    type: 'btc',
    vBytes: 140,
    range: ranges.btc,
  },
  eth: {
    key: 'eth',
    symbol: 'ETH',
    type: 'evm',
    gasLimit: 65000,
    range: ranges.eth,
    rpc: [
      'https://rpc.ankr.com/eth',
      'https://ethereum-rpc.publicnode.com',
      'https://cloudflare-eth.com',
    ],
    etherscan: 'https://api.etherscan.io/api?module=gastracker&action=gasoracle',
  },
  bsc: {
    key: 'bsc',
    symbol: 'BNB',
    type: 'evm',
    gasLimit: 65000,
    range: ranges.bsc,
    rpc: [
      'https://bsc-dataseed.binance.org',
      'https://bsc-rpc.publicnode.com',
      'https://rpc.ankr.com/bsc',
      'https://bsc-mainnet.public.blastapi.io',
    ],
    etherscan: 'https://api.bscscan.com/api?module=gastracker&action=gasoracle',
  },
  polygon: {
    key: 'polygon',
    symbol: 'MATIC',
    type: 'evm',
    gasLimit: 65000,
    range: ranges.polygon,
    rpc: [
      'https://polygon-rpc.com',
      'https://polygon-bor.publicnode.com',
      'https://rpc.ankr.com/polygon',
      'https://rpc-mainnet.matic.quiknode.pro',
    ],
    etherscan: 'https://api.polygonscan.com/api?module=gastracker&action=gasoracle',
  },
  avax: {
    key: 'avax',
    symbol: 'AVAX',
    type: 'evm',
    gasLimit: 65000,
    range: ranges.avax,
    rpc: [
      'https://api.avax.network/ext/bc/C/rpc',
      'https://avalanche-c-chain.publicnode.com',
      'https://rpc.ankr.com/avalanche',
      'https://ava-mainnet.public.blastapi.io/ext/bc/C/rpc',
    ],
    etherscan: 'https://api.snowtrace.io/api?module=gastracker&action=gasoracle',
  },
  gnosis: {
    key: 'gnosis',
    symbol: 'GNO',
    type: 'evm',
    gasLimit: 65000,
    range: ranges.gnosis,
    rpc: [
      'https://rpc.gnosischain.com',
      'https://gnosis-rpc.publicnode.com',
      'https://rpc.ankr.com/gnosis',
    ],
  },
  fantom: {
    key: 'fantom',
    symbol: 'FTM',
    type: 'evm',
    gasLimit: 65000,
    range: ranges.fantom,
    rpc: [
      'https://rpc.ftm.tools',
      'https://fantom-rpc.publicnode.com',
      'https://rpc.ankr.com/fantom',
    ],
  },
  cronos: {
    key: 'cronos',
    symbol: 'CRO',
    type: 'evm',
    gasLimit: 65000,
    range: ranges.cronos,
    rpc: [
      'https://evm.cronos.org',
      'https://cronos-rpc.publicnode.com',
      'https://rpc.ankr.com/cronos',
    ],
  },
  sol: {
    key: 'sol',
    symbol: 'SOL',
    type: 'sol',
    range: ranges.sol,
    rpc: [
      'https://api.mainnet-beta.solana.com',
      'https://rpc.ankr.com/solana',
      'https://solana-mainnet.g.alchemy.com/v2/demo',
    ],
  },
  xrp: {
    key: 'xrp',
    symbol: 'XRP',
    type: 'xrp',
    range: ranges.xrp,
    rpc: 'https://s1.ripple.com:51234',
  },
  arb: {
    key: 'arb',
    symbol: 'ETH',
    type: 'l2',
    gasLimitL2: 65000,
    l1DataGas: 30000,
    range: ranges.arb,
    rpc: [
      'https://arb1.arbitrum.io/rpc',
      'https://arbitrum-one.publicnode.com',
      'https://rpc.ankr.com/arbitrum',
    ],
  },
  op: {
    key: 'op',
    symbol: 'ETH',
    type: 'l2',
    gasLimitL2: 65000,
    l1DataGas: 30000,
    range: ranges.op,
    rpc: [
      'https://mainnet.optimism.io',
      'https://optimism-rpc.publicnode.com',
      'https://rpc.ankr.com/optimism',
    ],
  },
  base: {
    key: 'base',
    symbol: 'ETH',
    type: 'l2',
    gasLimitL2: 65000,
    l1DataGas: 30000,
    range: ranges.base,
    rpc: [
      'https://mainnet.base.org',
      'https://base-rpc.publicnode.com',
      'https://rpc.ankr.com/base',
    ],
  },
};
